---
- name: restart sshd
  systemd:
    name: ssh.service
    state: restarted
    daemon_reload: yes

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: reload ufw
  ufw:
    state: reloaded
