name: CI/CD DevForge
permissions:
  contents: read
  issues: write
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests
        working-directory: ./app
        run: go test ./... -v

  security-sast:
    name: SAST (gosec)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run gosec
        uses: securego/gosec@master
        with:
          args: ./app/...

  build-scan-push:
    name: Build + Trivy + Push
    runs-on: ubuntu-latest
    needs: [test, security-sast]
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        working-directory: ./app
        run: docker build -t caza6367/devforge-api:${{ github.sha }} .

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: caza6367/devforge-api:${{ github.sha }}
          format: table
          exit-code: '1'
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker tag caza6367/devforge-api:${{ github.sha }} caza6367/devforge-api:latest
          docker push caza6367/devforge-api:${{ github.sha }}
          docker push caza6367/devforge-api:latest

  dast-zap:
    name: DAST (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: [build-scan-push]
    steps:
      - uses: actions/checkout@v4

      - name: Subir Redis
        run: docker run -d --name redis -p 6379:6379 redis:alpine

      - name: Subir Vault dev
        run: |
          docker run -d --name vault \
            -p 8200:8200 \
            -e 'VAULT_DEV_ROOT_TOKEN_ID=devtoken' \
            -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200' \
            hashicorp/vault
          sleep 5
          docker exec -e VAULT_ADDR=http://127.0.0.1:8200 -e VAULT_TOKEN=devtoken vault \
            vault kv put secret/devforge aes_key='12345678901234567890123456789012'

      - name: Subir API
        run: |
          docker run -d --name api --network host \
            -e VAULT_ADDR=http://127.0.0.1:8200 \
            -e VAULT_TOKEN=devtoken \
            -e REDIS_ADDR=127.0.0.1:6379 \
            caza6367/devforge-api:latest
          sleep 5
          curl -s http://localhost:8080/health

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-a'
          fail_action: false
